---
backend:
  name: git-gateway
media_folder: static/img
public_folder: /img
collections:
  -
    label: Pages
    name: pages
    files:
      -
        file: data/intro.md
        label: Intro
        name: intro
        fields:
          -
            default: intro
            label: "Template Key"
            name: templateKey
            widget: hidden
          -
            hint: The background image to display on the "About Us" section.
            label: Background Image
            name: backgroundImage
            widget: image
          -
            label: English
            name: english
            widget: object
            fields:
              -
                hint: The introduction text that displays next to the dictionary definition.
                label: Intro
                name: intro
                widget: string
              -
                default: Our Story
                hint: The heading text for the "About Us" section.
                label: Heading
                name: heading
                widget: string
              -
                hint: The primary content of the "About Us" section.
                label: Content
                name: content
                widget: string
          -
            label: Vietnamese
            name: vietnamese
            widget: object
            fields:
              -
                hint: The introduction text that displays next to the dictionary definition.
                label: Intro
                name: intro
                widget: string
              -
                default: Our Story
                hint: The heading text for the "About Us" section.
                label: Heading
                name: heading
                widget: string
              -
                hint: The primary content of the "About Us" section.
                label: Content
                name: content
                widget: string
      -
        file: data/founders.md
        label: Founders
        name: founders
        fields:
          -
            default: founders
            label: "Template Key"
            name: templateKey
            widget: hidden
          -
            label: English
            name: english
            widget: object
            fields:
              -
                default: The Founders
                hint: The heading text for the "Founders" section.
                label: Heading
                name: heading
                required: true
                widget: string
          -
            label: Vietnamese
            name: vietnamese
            widget: object
            fields:
              -
                default: The Founders
                hint: The heading text for the "Founders" section.
                label: Heading
                name: heading
                required: true
                widget: string
          -
            label: The Founders
            name: foundersList
            widget: list
            fields:
              -
                hint: The profile image of the Founder.
                label: image
                name: image
                required: true
                widget: image
              -
                hint: The hex code for the background color for the Founder.
                label: background
                name: backgroundColor
                required: true
                widget: string
              -
                hint: The full name of the Founder.
                label: Full Name
                name: fullName
                required: true
                widget: string
              -
                label: English
                name: english
                required: true
                widget: object
                fields:
                  -
                    hint: The job title of the Founder.
                    label: Job Title
                    name: jobTitle
                    required: true
                    widget: string
                  -
                    hint: The job description of the Founder.
                    label: Job Description
                    name: jobDescription
                    required: true
                    widget: string
              -
                label: Vietnamese
                name: vietnamese
                required: true
                widget: object
                fields:
                  -
                    hint: The job title of the Founder.
                    label: Job Title
                    name: jobTitle
                    required: true
                    widget: string
                  -
                    hint: The job description of the Founder.
                    label: Job Description
                    name: jobDescription
                    required: true
                    widget: string
              -
                hint: A list of fun favorite things for each Founder. No Vietnamese translation here as it's not necessary
                label: Favorites
                name: favorites
                required: true
                widget: object
                fields:
                  -
                    hint: Favorite style of beer
                    label: Beer Style
                    name: beerStyle
                    required: true
                    widget: string
                  -
                    label: Breweries
                    name: breweries
                    required: true
                    widget: list
                    fields:
                      -
                        hint: The name of the brewery
                        label: Brewery Name
                        name: breweryName
                        required: true
                        widget: string
                      -
                        hint: The url for the brewery's website
                        label: Brewery URL
                        name: breweryUrl
                        widget: string
                  -
                    label: Other
                    name: other
                    required: true
                    widget: object
                    fields:
                      -
                        label: Classifier
                        name: classifier
                        required: true
                        widget: string
                      -
                        label: favorite
                        name: favorite
                        required: true
                        widget: string
      -
        file: data/beers.md
        label: Beers
        name: beers
        fields:
          -
            default: beers
            label: "Template Key"
            name: templateKey
            widget: hidden
          -
            label: English
            name: english
            widget: object
            fields:
              -
                default: Our Beers
                hint: The heading text for the "Beers" section.
                label: Heading
                name: heading
                required: true
                widget: string
              -
                default: Aroma & Taste
                hint: The text displayed for the "Aroma & Taste" section of each beer.
                label: Aroma and Taste Heading
                name: aromaAndTasteHeading
                required: true
                widget: string
          -
            label: Vietnamese
            name: vietnamese
            widget: object
            fields:
              -
                default: The Founders
                hint: The heading text for the "Beers" section.
                label: Heading
                name: heading
                required: true
                widget: string
              -
                default: Aroma & Taste
                hint: The text displayed for the "Aroma & Taste" section of each beer.
                label: Aroma and Taste Heading
                name: aromaAndTasteHeading
                required: true
                widget: string
          -
            label: Beers
            name: beerList
            widget: list
            fields:
              -
                hint: The bottle image for the beer.
                label: Bottle Image
                name: bottleImage
                required: true
                widget: image
              -
                hint: The image of the beer's stylized name.
                label: Name Image
                name: nameImage
                required: true
                widget: image
              -
                hint: The hex code for the accent color of the beer.
                label: Accent Color
                name: accentColor
                required: true
                widget: string
              -
                hint: The name of the beer.
                label: Name
                name: name
                required: true
                widget: string
              -
                label: English
                name: english
                required: true
                widget: object
                fields:
                  -
                    hint: The introduction text for the beer.
                    label: Intro
                    name: intro
                    required: true
                    widget: string
                  -
                    hint: The description for the beer.
                    label: Description
                    name: description
                    required: true
                    widget: markdown
                  -
                    hint: The aroma and taste notes for the beer.
                    label: Aroma and Taste
                    name: aromaAndTaste
                    required: true
                    widget: string
                  -
                    hint: The grains used in the beer, separated by comma.
                    label: Grains
                    name: grains
                    required: true
                    widget: list
                  -
                    hint: The hops used in the beer, separated by comma.
                    label: Hops
                    name: hops
                    required: true
                    widget: list
                  -
                    hint: The yeast used in the beer, separated by comma.
                    label: Yeast
                    name: yeast
                    required: true
                    widget: list
              -
                label: Vietnamese
                name: vietnamese
                required: true
                widget: object
                fields:
                  -
                    hint: The introduction text for the beer.
                    label: Intro
                    name: intro
                    required: true
                    widget: string
                  -
                    hint: The description for the beer.
                    label: Description
                    name: description
                    required: true
                    widget: markdown
                  -
                    hint: The aroma and taste notes for the beer.
                    label: Aroma and Taste
                    name: aromaAndTaste
                    required: true
                    widget: string
                  -
                    hint: The grains used in the beer, separated by comma.
                    label: Grains
                    name: grains
                    required: true
                    widget: list
                  -
                    hint: The hops used in the beer, separated by comma.
                    label: Hops
                    name: hops
                    required: true
                    widget: list
                  -
                    hint: The yeast used in the beer, separated by comma.
                    label: Yeast
                    name: yeast
                    required: true
                    widget: list
