---
backend:
  branch: master
  name: git-gateway
media_folder: static/img
public_folder: /img
collections:
  -
    create: true
    fields:
      -
        default: founder
        label: "Template Key"
        name: templateKey
        widget: hidden
      -
        label: Full Name
        name: title
        widget: string
      -
        label: Job Title
        name: jobTitle
        widget: string
      -
        label: Image
        name: image
        widget: image

      -
        label: Position
        name: position
        valueType: Int
        widget: number
    folder: data/founders
    label: Founders
    name: founders
    slug: "{{position}}-{{title}}"
  -
    create: true
    fields:
      -
        default: mainstay
        label: "Template Key"
        name: templateKey
        widget: hidden
      -
        label: Title
        name: title
        widget: string
      -
        label: "Name Image"
        name: nameImage
        widget: image
      -
        label: "Bottle Image"
        name: bottleImage
        widget: image
      -
        label: Position
        name: position
        valueType: Int
        widget: number
      -
        label: Introduction
        name: introduction
        widget: string
      -
        label: "Description"
        name: description
        widget: markdown
      -
        fields:
          -
            label: "Aroma & Taste"
            name: aromaAndTaste
            widget: string
          -
            label: ABV
            name: abv
            widget: string
          -
            label: OG
            name: og
            widget: string
          -
            label: Grains
            name: grains
            widget: string
          -
            label: Hops
            name: hops
            widget: string
          -
            label: Yeast
            name: yeast
            widget: string
        label: "Flavor Profile"
        name: flavorProfile
        widget: object
      -
        fields:
          - label: "Accent"
            name: accent
            widget: string
          -
            label: "Accent Dark"
            name: accentDark
            widget: string
          -
            label: "Accent Light"
            name: accentLight
            widget: string
        label: Style
        name: style
        widget: object
    folder: data/mainstays
    label: "Mainstay Beers"
    name: mainstayBeers
    slug: "{{position}}-{{title}}"
  -
    label: Pages
    name: pages
    files:
      -
        file: data/intro.md
        label: Intro
        name: intro
        fields:
          -
            default: intro
            label: "Template Key"
            name: templateKey
            widget: hidden
          -
            label: Heading
            name: heading
            widget: string
          -
            label: Description
            name: description
            widget: string
          -
            label: Dictionary
            name: dictionary
            widget: object
            fields:
              -
                label: Title
                name: title
                widget: string
              -
                label: Phonetic
                name: phonetic
                widget: string
              -
                label: Defintion
                name: definition
                widget: string
              -
                label: Source
                name: source
                widget: string
      -
        file: data/about.md
        label: About
        name: about
        fields:
          -
            default: about
            label: "Template Key"
            name: templateKey
            widget: hidden
          -
            label: Introduction
            name: introduction
            widget: markdown
          -
            default: content
            label: Content
            name: content
            widget: markdown
      -
        file: data/subscribe.md
        label: Subscribe
        name: subscribe
        fields:
          -
            default: subscribe
            label: "Template Key"
            name: templateKey
            widget: hidden
          -
            label: Content
            name: content
            widget: string
          -
            label: "Button Text"
            name: buttonText
            widget: string
      -
        file: data/footer.md
        label: Footer
        name: footer
        fields:
          -
            default: footer
            label: "Template Key"
            name: templateKey
            widget: hidden
          -
            label: "English Company Name"
            name: englishCompanyName
            widget: string
          -
            label: "Vietnamese Company Name"
            name: vietnameseCompanyName
            widget: string
          -
            label: Address
            name: address
            widget: string
          -
            label: Email
            name: email
            widget: string
          -
            label: "Legal Text"
            name: legalText
            widget: string
      -
        file: data/assets.md
        label: Assets
        name: assets
        fields:
          -
            default: assets
            label: "Template Key"
            name: templateKey
            widget: hidden
          -
            label: "Text Logo"
            name: textLogo
            widget: image
          -
            label: "Image Logo"
            name: imageLogo
            widget: image
          - label: "Combined Logo"
